services:

  postgres:
    image: postgres:17-alpine
    container_name: associados-postgres
    environment:
      POSTGRES_DB: associados
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./etc/postgres/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh


volumes:
  postgres_data: