spring:
  application:
    name: associados

  datasource:
    url: jdbc:postgresql://localhost:5432/associados
    username: postgres
    password: postgres

  jpa:
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration,classpath:db/testdata,classpath:db/testdata
    user: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/associados
