create table public.company (
  id uuid not null,
  document varchar(255),
  email varchar(255),
  name varchar(255),
  phone varchar(255),
  associate_tax numeric(15, 2),
  day_base integer,
  address_city varchar(255),
  address_complement varchar(255),
  address_neighborhood varchar(255),
  address_number varchar(255),
  address_state varchar(255),
  address_street varchar(255),
  address_zip_code varchar(255),
  created_at timestamp with time zone,
  constraint uq_company_email unique (email),
  constraint uq_company_document unique (document),
  primary key (id)
);